A *set* is a collection of different things. The things contained in a set are called *elements* or *members*. To denote the membership of $a$ to a set $A$ we write $a\in A$ and read "a belongs in A" or "a is in A". If we want to indicate that $a$ is not a member of $A$, we write $a\not\in A$ and read "a does not belong in A" or "a is not in A". A set without elements is called the empty set, and it is denoted by $\emptyset$. 
#+hugo: more

#+attr_shortcode: :type examples
#+begin_activity
 - A collection of four natural numbers
$$ A = \left\{4, 2, 1, 3\right\} $$
 - A collection of colors
$$ B = \left\{\text{blue, white, red}\right\} $$
 - The set of natural numbers
$$ \mathbb{N} = \left\{1, 2, 3, \dots \right\} $$
 - The set of integers
$$ \mathbb{Z} = \left\{\dots, -3, -2, -1, 0, 1, 2, 3, \dots \right\} $$
 - The set of rational numbers
$$ \mathbb{Q} = \left\{\frac{z}{n}\colon\, z\in\mathbb{Z}, \, n\in\mathbb{N}  \right\} $$
 - The set of real numbers
$$ \mathbb{R} = \text{...needs more concepts to be described.} $$
 - The set of solutions of the parabola $2x^{2}-6x + 4 = 0$
$$ S = \left\{x\in \mathbb{R} \colon\, 2x^{2}-6x + 4 = 0  \right\} = \left\{1, 2\right\} $$
#+end_activity

Inclusion operators can be defined for sets. If every element of a set $A$ is a member of a set $B$, we write $A\subseteq B$ and say that "A is a subset of B". We can also say that "B is a superset of A". Two sets $A$ and $B$ are equal if they have exactly the same elements, i.e., $A \subseteq B$ and $B \subseteq A$. We then write $A = B$.

* Cartesian Products
The *Cartesian product* of two sets $A$ and $B$ is a set with elements pairs combining an element of $A$ and an element of $B$. Specifically, we write
$$
A \times B = \left\{(a,b)\colon\, a\in A,\, b\in B\right\}.
$$
Elements of the Cartesian product are denoted by $(a,b)\in A\times B$. Cartesian products are analogously defined of any finite collection of $n$ sets. For example,
$$
\times_{i=1}^{n} X_{i} = \left\{(x_{1}, \dots, x_{n})\colon\, x_{1}\in X_{1},\, \dots,\, x_{n}\in X_{n}\right\}.
$$

#+attr_shortcode: :type example
#+begin_activity
Cartesian products are frequently used in economics and finance. For example, consider a situation where one would like to choose the amount of money invested in stocks and bonds. For simplicity, let $X_{1} = \mathbb{R}_{\ge 0}$ be the set of potential stock investments in Euros, and $X_{2} = \mathbb{R}_{\ge 0}$ be the set of potential bond investments in Euros (short sales are excluded). The Cartesian product $X_{1}\times X_{2}$ is known as the /investment opportunity set/ in finance, i.e., the set containing all investment choices available to an economic entity.
#+end_activity

* Convex Combinations and Convex Sets
It is rare for economic choices to be made in isolation. When a person visits a retail store, she purchases a variety of products instead of a single one on most occasions. In production settings, entrepreneurs combine labor, capital, and other production factors to produce the desired output. In addition, entrepreneurs have to consider not only a particular pair of labor and capital but rather how this pair compares to other feasible pairs of capital and labor they could employ in production. A commonly used way (for reasons going beyond this introduction's scope) to mathematically describe such collections of choices is via their convex combinations. For any real number $\alpha\in[0,1]$, and any two points $x_{1}, x_{2} \in X$, we say that $x = \alpha x_{1} + (1 - \alpha) x_{2}$ is a *convex combination* of $x_{1}$ and $x_{2}$.

{{{figure(convexity,methods,convexity_graph)}}}

We say that a set $X$ is convex if it contains all the convex combinations of its elements. Namely, $X$ is a *convex set* if for every $\alpha\in[0,1]$, and every $x_{1}, x_{2} \in X$, we have $\alpha x_{1} + (1 - \alpha) x_{2} \in X$.


